FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    make \
    git \
    libgnutls28-dev \
    libcurl4-gnutls-dev \
    python3-pycurl \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app
WORKDIR /app

COPY setup.py .
COPY versioneer.py .
COPY setup.cfg .
COPY xirt/ xirt/
COPY requirements_polars.txt .

RUN pip install -r requirements_polars.txt
RUN pip install .

RUN chmod -R a+rw /app

ENV TF_CPP_MIN_LOG_LEVEL=1

ENTRYPOINT ["python", "-m", "xirt"]
